//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarAppWebClient.MyAnnouncesService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyAnnouncesService.MyAnnouncesServicesSoap")]
    public interface MyAnnouncesServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PopulateGrid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet PopulateGrid(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PopulateGrid", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> PopulateGridAsync(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteAnnounce", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void deleteAnnounce(int idAnnounce);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteAnnounce", ReplyAction="*")]
        System.Threading.Tasks.Task deleteAnnounceAsync(int idAnnounce);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyAnnouncesServicesSoapChannel : CarAppWebClient.MyAnnouncesService.MyAnnouncesServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyAnnouncesServicesSoapClient : System.ServiceModel.ClientBase<CarAppWebClient.MyAnnouncesService.MyAnnouncesServicesSoap>, CarAppWebClient.MyAnnouncesService.MyAnnouncesServicesSoap {
        
        public MyAnnouncesServicesSoapClient() {
        }
        
        public MyAnnouncesServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyAnnouncesServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyAnnouncesServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyAnnouncesServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet PopulateGrid(int idUser) {
            return base.Channel.PopulateGrid(idUser);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> PopulateGridAsync(int idUser) {
            return base.Channel.PopulateGridAsync(idUser);
        }
        
        public void deleteAnnounce(int idAnnounce) {
            base.Channel.deleteAnnounce(idAnnounce);
        }
        
        public System.Threading.Tasks.Task deleteAnnounceAsync(int idAnnounce) {
            return base.Channel.deleteAnnounceAsync(idAnnounce);
        }
    }
}
