//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarAppWebClient.CreateAccountService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreateAccountService.CreateAccountSoap")]
    public interface CreateAccountSoap {
        
        // CODEGEN: Generating message contract since element name nume from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createUserAcount", ReplyAction="*")]
        CarAppWebClient.CreateAccountService.createUserAcountResponse createUserAcount(CarAppWebClient.CreateAccountService.createUserAcountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createUserAcount", ReplyAction="*")]
        System.Threading.Tasks.Task<CarAppWebClient.CreateAccountService.createUserAcountResponse> createUserAcountAsync(CarAppWebClient.CreateAccountService.createUserAcountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createUserAcountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createUserAcount", Namespace="http://tempuri.org/", Order=0)]
        public CarAppWebClient.CreateAccountService.createUserAcountRequestBody Body;
        
        public createUserAcountRequest() {
        }
        
        public createUserAcountRequest(CarAppWebClient.CreateAccountService.createUserAcountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createUserAcountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prenume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string parola;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string adresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string telefon;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public byte[] userImage;
        
        public createUserAcountRequestBody() {
        }
        
        public createUserAcountRequestBody(string nume, string prenume, string email, string parola, string adresa, string telefon, byte[] userImage) {
            this.nume = nume;
            this.prenume = prenume;
            this.email = email;
            this.parola = parola;
            this.adresa = adresa;
            this.telefon = telefon;
            this.userImage = userImage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createUserAcountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createUserAcountResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarAppWebClient.CreateAccountService.createUserAcountResponseBody Body;
        
        public createUserAcountResponse() {
        }
        
        public createUserAcountResponse(CarAppWebClient.CreateAccountService.createUserAcountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createUserAcountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool createUserAcountResult;
        
        public createUserAcountResponseBody() {
        }
        
        public createUserAcountResponseBody(bool createUserAcountResult) {
            this.createUserAcountResult = createUserAcountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CreateAccountSoapChannel : CarAppWebClient.CreateAccountService.CreateAccountSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateAccountSoapClient : System.ServiceModel.ClientBase<CarAppWebClient.CreateAccountService.CreateAccountSoap>, CarAppWebClient.CreateAccountService.CreateAccountSoap {
        
        public CreateAccountSoapClient() {
        }
        
        public CreateAccountSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreateAccountSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateAccountSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateAccountSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarAppWebClient.CreateAccountService.createUserAcountResponse CarAppWebClient.CreateAccountService.CreateAccountSoap.createUserAcount(CarAppWebClient.CreateAccountService.createUserAcountRequest request) {
            return base.Channel.createUserAcount(request);
        }
        
        public bool createUserAcount(string nume, string prenume, string email, string parola, string adresa, string telefon, byte[] userImage) {
            CarAppWebClient.CreateAccountService.createUserAcountRequest inValue = new CarAppWebClient.CreateAccountService.createUserAcountRequest();
            inValue.Body = new CarAppWebClient.CreateAccountService.createUserAcountRequestBody();
            inValue.Body.nume = nume;
            inValue.Body.prenume = prenume;
            inValue.Body.email = email;
            inValue.Body.parola = parola;
            inValue.Body.adresa = adresa;
            inValue.Body.telefon = telefon;
            inValue.Body.userImage = userImage;
            CarAppWebClient.CreateAccountService.createUserAcountResponse retVal = ((CarAppWebClient.CreateAccountService.CreateAccountSoap)(this)).createUserAcount(inValue);
            return retVal.Body.createUserAcountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarAppWebClient.CreateAccountService.createUserAcountResponse> CarAppWebClient.CreateAccountService.CreateAccountSoap.createUserAcountAsync(CarAppWebClient.CreateAccountService.createUserAcountRequest request) {
            return base.Channel.createUserAcountAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarAppWebClient.CreateAccountService.createUserAcountResponse> createUserAcountAsync(string nume, string prenume, string email, string parola, string adresa, string telefon, byte[] userImage) {
            CarAppWebClient.CreateAccountService.createUserAcountRequest inValue = new CarAppWebClient.CreateAccountService.createUserAcountRequest();
            inValue.Body = new CarAppWebClient.CreateAccountService.createUserAcountRequestBody();
            inValue.Body.nume = nume;
            inValue.Body.prenume = prenume;
            inValue.Body.email = email;
            inValue.Body.parola = parola;
            inValue.Body.adresa = adresa;
            inValue.Body.telefon = telefon;
            inValue.Body.userImage = userImage;
            return ((CarAppWebClient.CreateAccountService.CreateAccountSoap)(this)).createUserAcountAsync(inValue);
        }
    }
}
