//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarAppWebClient.CreateAccountService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreateAccountService.CreateAccountSoap")]
    public interface CreateAccountSoap {
        
        // CODEGEN: Generating message contract since element name nume from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createUserAccount", ReplyAction="*")]
        CarAppWebClient.CreateAccountService.createUserAccountResponse createUserAccount(CarAppWebClient.CreateAccountService.createUserAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createUserAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<CarAppWebClient.CreateAccountService.createUserAccountResponse> createUserAccountAsync(CarAppWebClient.CreateAccountService.createUserAccountRequest request);
        
        // CODEGEN: Generating message contract since element name nume from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createAdminAccount", ReplyAction="*")]
        CarAppWebClient.CreateAccountService.createAdminAccountResponse createAdminAccount(CarAppWebClient.CreateAccountService.createAdminAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createAdminAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<CarAppWebClient.CreateAccountService.createAdminAccountResponse> createAdminAccountAsync(CarAppWebClient.CreateAccountService.createAdminAccountRequest request);
        
        // CODEGEN: Generating message contract since element name pass from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkPass", ReplyAction="*")]
        CarAppWebClient.CreateAccountService.checkPassResponse checkPass(CarAppWebClient.CreateAccountService.checkPassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkPass", ReplyAction="*")]
        System.Threading.Tasks.Task<CarAppWebClient.CreateAccountService.checkPassResponse> checkPassAsync(CarAppWebClient.CreateAccountService.checkPassRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createUserAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createUserAccount", Namespace="http://tempuri.org/", Order=0)]
        public CarAppWebClient.CreateAccountService.createUserAccountRequestBody Body;
        
        public createUserAccountRequest() {
        }
        
        public createUserAccountRequest(CarAppWebClient.CreateAccountService.createUserAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createUserAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prenume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string parola;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string adresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string telefon;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public byte[] userImage;
        
        public createUserAccountRequestBody() {
        }
        
        public createUserAccountRequestBody(string nume, string prenume, string email, string parola, string adresa, string telefon, byte[] userImage) {
            this.nume = nume;
            this.prenume = prenume;
            this.email = email;
            this.parola = parola;
            this.adresa = adresa;
            this.telefon = telefon;
            this.userImage = userImage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createUserAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createUserAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarAppWebClient.CreateAccountService.createUserAccountResponseBody Body;
        
        public createUserAccountResponse() {
        }
        
        public createUserAccountResponse(CarAppWebClient.CreateAccountService.createUserAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createUserAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool createUserAccountResult;
        
        public createUserAccountResponseBody() {
        }
        
        public createUserAccountResponseBody(bool createUserAccountResult) {
            this.createUserAccountResult = createUserAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createAdminAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createAdminAccount", Namespace="http://tempuri.org/", Order=0)]
        public CarAppWebClient.CreateAccountService.createAdminAccountRequestBody Body;
        
        public createAdminAccountRequest() {
        }
        
        public createAdminAccountRequest(CarAppWebClient.CreateAccountService.createAdminAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createAdminAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prenume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string parola;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string contact;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] userImage;
        
        public createAdminAccountRequestBody() {
        }
        
        public createAdminAccountRequestBody(string nume, string prenume, string email, string parola, string contact, byte[] userImage) {
            this.nume = nume;
            this.prenume = prenume;
            this.email = email;
            this.parola = parola;
            this.contact = contact;
            this.userImage = userImage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createAdminAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createAdminAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarAppWebClient.CreateAccountService.createAdminAccountResponseBody Body;
        
        public createAdminAccountResponse() {
        }
        
        public createAdminAccountResponse(CarAppWebClient.CreateAccountService.createAdminAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createAdminAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool createAdminAccountResult;
        
        public createAdminAccountResponseBody() {
        }
        
        public createAdminAccountResponseBody(bool createAdminAccountResult) {
            this.createAdminAccountResult = createAdminAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkPassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkPass", Namespace="http://tempuri.org/", Order=0)]
        public CarAppWebClient.CreateAccountService.checkPassRequestBody Body;
        
        public checkPassRequest() {
        }
        
        public checkPassRequest(CarAppWebClient.CreateAccountService.checkPassRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkPassRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pass;
        
        public checkPassRequestBody() {
        }
        
        public checkPassRequestBody(string pass) {
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkPassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkPassResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarAppWebClient.CreateAccountService.checkPassResponseBody Body;
        
        public checkPassResponse() {
        }
        
        public checkPassResponse(CarAppWebClient.CreateAccountService.checkPassResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkPassResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool checkPassResult;
        
        public checkPassResponseBody() {
        }
        
        public checkPassResponseBody(bool checkPassResult) {
            this.checkPassResult = checkPassResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CreateAccountSoapChannel : CarAppWebClient.CreateAccountService.CreateAccountSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateAccountSoapClient : System.ServiceModel.ClientBase<CarAppWebClient.CreateAccountService.CreateAccountSoap>, CarAppWebClient.CreateAccountService.CreateAccountSoap {
        
        public CreateAccountSoapClient() {
        }
        
        public CreateAccountSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreateAccountSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateAccountSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateAccountSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarAppWebClient.CreateAccountService.createUserAccountResponse CarAppWebClient.CreateAccountService.CreateAccountSoap.createUserAccount(CarAppWebClient.CreateAccountService.createUserAccountRequest request) {
            return base.Channel.createUserAccount(request);
        }
        
        public bool createUserAccount(string nume, string prenume, string email, string parola, string adresa, string telefon, byte[] userImage) {
            CarAppWebClient.CreateAccountService.createUserAccountRequest inValue = new CarAppWebClient.CreateAccountService.createUserAccountRequest();
            inValue.Body = new CarAppWebClient.CreateAccountService.createUserAccountRequestBody();
            inValue.Body.nume = nume;
            inValue.Body.prenume = prenume;
            inValue.Body.email = email;
            inValue.Body.parola = parola;
            inValue.Body.adresa = adresa;
            inValue.Body.telefon = telefon;
            inValue.Body.userImage = userImage;
            CarAppWebClient.CreateAccountService.createUserAccountResponse retVal = ((CarAppWebClient.CreateAccountService.CreateAccountSoap)(this)).createUserAccount(inValue);
            return retVal.Body.createUserAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarAppWebClient.CreateAccountService.createUserAccountResponse> CarAppWebClient.CreateAccountService.CreateAccountSoap.createUserAccountAsync(CarAppWebClient.CreateAccountService.createUserAccountRequest request) {
            return base.Channel.createUserAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarAppWebClient.CreateAccountService.createUserAccountResponse> createUserAccountAsync(string nume, string prenume, string email, string parola, string adresa, string telefon, byte[] userImage) {
            CarAppWebClient.CreateAccountService.createUserAccountRequest inValue = new CarAppWebClient.CreateAccountService.createUserAccountRequest();
            inValue.Body = new CarAppWebClient.CreateAccountService.createUserAccountRequestBody();
            inValue.Body.nume = nume;
            inValue.Body.prenume = prenume;
            inValue.Body.email = email;
            inValue.Body.parola = parola;
            inValue.Body.adresa = adresa;
            inValue.Body.telefon = telefon;
            inValue.Body.userImage = userImage;
            return ((CarAppWebClient.CreateAccountService.CreateAccountSoap)(this)).createUserAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarAppWebClient.CreateAccountService.createAdminAccountResponse CarAppWebClient.CreateAccountService.CreateAccountSoap.createAdminAccount(CarAppWebClient.CreateAccountService.createAdminAccountRequest request) {
            return base.Channel.createAdminAccount(request);
        }
        
        public bool createAdminAccount(string nume, string prenume, string email, string parola, string contact, byte[] userImage) {
            CarAppWebClient.CreateAccountService.createAdminAccountRequest inValue = new CarAppWebClient.CreateAccountService.createAdminAccountRequest();
            inValue.Body = new CarAppWebClient.CreateAccountService.createAdminAccountRequestBody();
            inValue.Body.nume = nume;
            inValue.Body.prenume = prenume;
            inValue.Body.email = email;
            inValue.Body.parola = parola;
            inValue.Body.contact = contact;
            inValue.Body.userImage = userImage;
            CarAppWebClient.CreateAccountService.createAdminAccountResponse retVal = ((CarAppWebClient.CreateAccountService.CreateAccountSoap)(this)).createAdminAccount(inValue);
            return retVal.Body.createAdminAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarAppWebClient.CreateAccountService.createAdminAccountResponse> CarAppWebClient.CreateAccountService.CreateAccountSoap.createAdminAccountAsync(CarAppWebClient.CreateAccountService.createAdminAccountRequest request) {
            return base.Channel.createAdminAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarAppWebClient.CreateAccountService.createAdminAccountResponse> createAdminAccountAsync(string nume, string prenume, string email, string parola, string contact, byte[] userImage) {
            CarAppWebClient.CreateAccountService.createAdminAccountRequest inValue = new CarAppWebClient.CreateAccountService.createAdminAccountRequest();
            inValue.Body = new CarAppWebClient.CreateAccountService.createAdminAccountRequestBody();
            inValue.Body.nume = nume;
            inValue.Body.prenume = prenume;
            inValue.Body.email = email;
            inValue.Body.parola = parola;
            inValue.Body.contact = contact;
            inValue.Body.userImage = userImage;
            return ((CarAppWebClient.CreateAccountService.CreateAccountSoap)(this)).createAdminAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarAppWebClient.CreateAccountService.checkPassResponse CarAppWebClient.CreateAccountService.CreateAccountSoap.checkPass(CarAppWebClient.CreateAccountService.checkPassRequest request) {
            return base.Channel.checkPass(request);
        }
        
        public bool checkPass(string pass) {
            CarAppWebClient.CreateAccountService.checkPassRequest inValue = new CarAppWebClient.CreateAccountService.checkPassRequest();
            inValue.Body = new CarAppWebClient.CreateAccountService.checkPassRequestBody();
            inValue.Body.pass = pass;
            CarAppWebClient.CreateAccountService.checkPassResponse retVal = ((CarAppWebClient.CreateAccountService.CreateAccountSoap)(this)).checkPass(inValue);
            return retVal.Body.checkPassResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarAppWebClient.CreateAccountService.checkPassResponse> CarAppWebClient.CreateAccountService.CreateAccountSoap.checkPassAsync(CarAppWebClient.CreateAccountService.checkPassRequest request) {
            return base.Channel.checkPassAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarAppWebClient.CreateAccountService.checkPassResponse> checkPassAsync(string pass) {
            CarAppWebClient.CreateAccountService.checkPassRequest inValue = new CarAppWebClient.CreateAccountService.checkPassRequest();
            inValue.Body = new CarAppWebClient.CreateAccountService.checkPassRequestBody();
            inValue.Body.pass = pass;
            return ((CarAppWebClient.CreateAccountService.CreateAccountSoap)(this)).checkPassAsync(inValue);
        }
    }
}
