//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarAppWebClient.CreateAnnouncementService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreateAnnouncementService.CreateAnnouncementSoap")]
    public interface CreateAnnouncementSoap {
        
        // CODEGEN: Generating message contract since element name caroserie from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addAnnounce", ReplyAction="*")]
        CarAppWebClient.CreateAnnouncementService.addAnnounceResponse addAnnounce(CarAppWebClient.CreateAnnouncementService.addAnnounceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addAnnounce", ReplyAction="*")]
        System.Threading.Tasks.Task<CarAppWebClient.CreateAnnouncementService.addAnnounceResponse> addAnnounceAsync(CarAppWebClient.CreateAnnouncementService.addAnnounceRequest request);
        
        // CODEGEN: Generating message contract since element name caroserie from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateAnnouncee", ReplyAction="*")]
        CarAppWebClient.CreateAnnouncementService.updateAnnounceeResponse updateAnnouncee(CarAppWebClient.CreateAnnouncementService.updateAnnounceeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateAnnouncee", ReplyAction="*")]
        System.Threading.Tasks.Task<CarAppWebClient.CreateAnnouncementService.updateAnnounceeResponse> updateAnnounceeAsync(CarAppWebClient.CreateAnnouncementService.updateAnnounceeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAnnounceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addAnnounce", Namespace="http://tempuri.org/", Order=0)]
        public CarAppWebClient.CreateAnnouncementService.addAnnounceRequestBody Body;
        
        public addAnnounceRequest() {
        }
        
        public addAnnounceRequest(CarAppWebClient.CreateAnnouncementService.addAnnounceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addAnnounceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int iduser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string caroserie;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string marca;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string model;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string varianta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int pret;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int an;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int km;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int putere;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int puterekw;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string combustibil;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string cutieviteze;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public int cc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string culoare;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string locatie;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string descriere;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public byte[] imageAnnounce;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public byte[] image1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public byte[] image2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public byte[] image3;
        
        public addAnnounceRequestBody() {
        }
        
        public addAnnounceRequestBody(
                    int iduser, 
                    string caroserie, 
                    string marca, 
                    string model, 
                    string varianta, 
                    int pret, 
                    int an, 
                    int km, 
                    int putere, 
                    int puterekw, 
                    string combustibil, 
                    string cutieviteze, 
                    int cc, 
                    string culoare, 
                    string locatie, 
                    string descriere, 
                    byte[] imageAnnounce, 
                    byte[] image1, 
                    byte[] image2, 
                    byte[] image3) {
            this.iduser = iduser;
            this.caroserie = caroserie;
            this.marca = marca;
            this.model = model;
            this.varianta = varianta;
            this.pret = pret;
            this.an = an;
            this.km = km;
            this.putere = putere;
            this.puterekw = puterekw;
            this.combustibil = combustibil;
            this.cutieviteze = cutieviteze;
            this.cc = cc;
            this.culoare = culoare;
            this.locatie = locatie;
            this.descriere = descriere;
            this.imageAnnounce = imageAnnounce;
            this.image1 = image1;
            this.image2 = image2;
            this.image3 = image3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAnnounceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addAnnounceResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarAppWebClient.CreateAnnouncementService.addAnnounceResponseBody Body;
        
        public addAnnounceResponse() {
        }
        
        public addAnnounceResponse(CarAppWebClient.CreateAnnouncementService.addAnnounceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addAnnounceResponseBody {
        
        public addAnnounceResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateAnnounceeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateAnnouncee", Namespace="http://tempuri.org/", Order=0)]
        public CarAppWebClient.CreateAnnouncementService.updateAnnounceeRequestBody Body;
        
        public updateAnnounceeRequest() {
        }
        
        public updateAnnounceeRequest(CarAppWebClient.CreateAnnouncementService.updateAnnounceeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateAnnounceeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CodAnunt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string caroserie;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string marca;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string model;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string varianta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int pret;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int an;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int km;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int putere;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int puterekw;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string combustibil;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string cutieviteze;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public int cc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string culoare;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string locatie;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string descriere;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public byte[] imgannounce;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public byte[] img1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public byte[] img2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public byte[] img3;
        
        public updateAnnounceeRequestBody() {
        }
        
        public updateAnnounceeRequestBody(
                    int CodAnunt, 
                    string caroserie, 
                    string marca, 
                    string model, 
                    string varianta, 
                    int pret, 
                    int an, 
                    int km, 
                    int putere, 
                    int puterekw, 
                    string combustibil, 
                    string cutieviteze, 
                    int cc, 
                    string culoare, 
                    string locatie, 
                    string descriere, 
                    byte[] imgannounce, 
                    byte[] img1, 
                    byte[] img2, 
                    byte[] img3) {
            this.CodAnunt = CodAnunt;
            this.caroserie = caroserie;
            this.marca = marca;
            this.model = model;
            this.varianta = varianta;
            this.pret = pret;
            this.an = an;
            this.km = km;
            this.putere = putere;
            this.puterekw = puterekw;
            this.combustibil = combustibil;
            this.cutieviteze = cutieviteze;
            this.cc = cc;
            this.culoare = culoare;
            this.locatie = locatie;
            this.descriere = descriere;
            this.imgannounce = imgannounce;
            this.img1 = img1;
            this.img2 = img2;
            this.img3 = img3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateAnnounceeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateAnnounceeResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarAppWebClient.CreateAnnouncementService.updateAnnounceeResponseBody Body;
        
        public updateAnnounceeResponse() {
        }
        
        public updateAnnounceeResponse(CarAppWebClient.CreateAnnouncementService.updateAnnounceeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updateAnnounceeResponseBody {
        
        public updateAnnounceeResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CreateAnnouncementSoapChannel : CarAppWebClient.CreateAnnouncementService.CreateAnnouncementSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateAnnouncementSoapClient : System.ServiceModel.ClientBase<CarAppWebClient.CreateAnnouncementService.CreateAnnouncementSoap>, CarAppWebClient.CreateAnnouncementService.CreateAnnouncementSoap {
        
        public CreateAnnouncementSoapClient() {
        }
        
        public CreateAnnouncementSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreateAnnouncementSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateAnnouncementSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateAnnouncementSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarAppWebClient.CreateAnnouncementService.addAnnounceResponse CarAppWebClient.CreateAnnouncementService.CreateAnnouncementSoap.addAnnounce(CarAppWebClient.CreateAnnouncementService.addAnnounceRequest request) {
            return base.Channel.addAnnounce(request);
        }
        
        public void addAnnounce(
                    int iduser, 
                    string caroserie, 
                    string marca, 
                    string model, 
                    string varianta, 
                    int pret, 
                    int an, 
                    int km, 
                    int putere, 
                    int puterekw, 
                    string combustibil, 
                    string cutieviteze, 
                    int cc, 
                    string culoare, 
                    string locatie, 
                    string descriere, 
                    byte[] imageAnnounce, 
                    byte[] image1, 
                    byte[] image2, 
                    byte[] image3) {
            CarAppWebClient.CreateAnnouncementService.addAnnounceRequest inValue = new CarAppWebClient.CreateAnnouncementService.addAnnounceRequest();
            inValue.Body = new CarAppWebClient.CreateAnnouncementService.addAnnounceRequestBody();
            inValue.Body.iduser = iduser;
            inValue.Body.caroserie = caroserie;
            inValue.Body.marca = marca;
            inValue.Body.model = model;
            inValue.Body.varianta = varianta;
            inValue.Body.pret = pret;
            inValue.Body.an = an;
            inValue.Body.km = km;
            inValue.Body.putere = putere;
            inValue.Body.puterekw = puterekw;
            inValue.Body.combustibil = combustibil;
            inValue.Body.cutieviteze = cutieviteze;
            inValue.Body.cc = cc;
            inValue.Body.culoare = culoare;
            inValue.Body.locatie = locatie;
            inValue.Body.descriere = descriere;
            inValue.Body.imageAnnounce = imageAnnounce;
            inValue.Body.image1 = image1;
            inValue.Body.image2 = image2;
            inValue.Body.image3 = image3;
            CarAppWebClient.CreateAnnouncementService.addAnnounceResponse retVal = ((CarAppWebClient.CreateAnnouncementService.CreateAnnouncementSoap)(this)).addAnnounce(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarAppWebClient.CreateAnnouncementService.addAnnounceResponse> CarAppWebClient.CreateAnnouncementService.CreateAnnouncementSoap.addAnnounceAsync(CarAppWebClient.CreateAnnouncementService.addAnnounceRequest request) {
            return base.Channel.addAnnounceAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarAppWebClient.CreateAnnouncementService.addAnnounceResponse> addAnnounceAsync(
                    int iduser, 
                    string caroserie, 
                    string marca, 
                    string model, 
                    string varianta, 
                    int pret, 
                    int an, 
                    int km, 
                    int putere, 
                    int puterekw, 
                    string combustibil, 
                    string cutieviteze, 
                    int cc, 
                    string culoare, 
                    string locatie, 
                    string descriere, 
                    byte[] imageAnnounce, 
                    byte[] image1, 
                    byte[] image2, 
                    byte[] image3) {
            CarAppWebClient.CreateAnnouncementService.addAnnounceRequest inValue = new CarAppWebClient.CreateAnnouncementService.addAnnounceRequest();
            inValue.Body = new CarAppWebClient.CreateAnnouncementService.addAnnounceRequestBody();
            inValue.Body.iduser = iduser;
            inValue.Body.caroserie = caroserie;
            inValue.Body.marca = marca;
            inValue.Body.model = model;
            inValue.Body.varianta = varianta;
            inValue.Body.pret = pret;
            inValue.Body.an = an;
            inValue.Body.km = km;
            inValue.Body.putere = putere;
            inValue.Body.puterekw = puterekw;
            inValue.Body.combustibil = combustibil;
            inValue.Body.cutieviteze = cutieviteze;
            inValue.Body.cc = cc;
            inValue.Body.culoare = culoare;
            inValue.Body.locatie = locatie;
            inValue.Body.descriere = descriere;
            inValue.Body.imageAnnounce = imageAnnounce;
            inValue.Body.image1 = image1;
            inValue.Body.image2 = image2;
            inValue.Body.image3 = image3;
            return ((CarAppWebClient.CreateAnnouncementService.CreateAnnouncementSoap)(this)).addAnnounceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarAppWebClient.CreateAnnouncementService.updateAnnounceeResponse CarAppWebClient.CreateAnnouncementService.CreateAnnouncementSoap.updateAnnouncee(CarAppWebClient.CreateAnnouncementService.updateAnnounceeRequest request) {
            return base.Channel.updateAnnouncee(request);
        }
        
        public void updateAnnouncee(
                    int CodAnunt, 
                    string caroserie, 
                    string marca, 
                    string model, 
                    string varianta, 
                    int pret, 
                    int an, 
                    int km, 
                    int putere, 
                    int puterekw, 
                    string combustibil, 
                    string cutieviteze, 
                    int cc, 
                    string culoare, 
                    string locatie, 
                    string descriere, 
                    byte[] imgannounce, 
                    byte[] img1, 
                    byte[] img2, 
                    byte[] img3) {
            CarAppWebClient.CreateAnnouncementService.updateAnnounceeRequest inValue = new CarAppWebClient.CreateAnnouncementService.updateAnnounceeRequest();
            inValue.Body = new CarAppWebClient.CreateAnnouncementService.updateAnnounceeRequestBody();
            inValue.Body.CodAnunt = CodAnunt;
            inValue.Body.caroserie = caroserie;
            inValue.Body.marca = marca;
            inValue.Body.model = model;
            inValue.Body.varianta = varianta;
            inValue.Body.pret = pret;
            inValue.Body.an = an;
            inValue.Body.km = km;
            inValue.Body.putere = putere;
            inValue.Body.puterekw = puterekw;
            inValue.Body.combustibil = combustibil;
            inValue.Body.cutieviteze = cutieviteze;
            inValue.Body.cc = cc;
            inValue.Body.culoare = culoare;
            inValue.Body.locatie = locatie;
            inValue.Body.descriere = descriere;
            inValue.Body.imgannounce = imgannounce;
            inValue.Body.img1 = img1;
            inValue.Body.img2 = img2;
            inValue.Body.img3 = img3;
            CarAppWebClient.CreateAnnouncementService.updateAnnounceeResponse retVal = ((CarAppWebClient.CreateAnnouncementService.CreateAnnouncementSoap)(this)).updateAnnouncee(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarAppWebClient.CreateAnnouncementService.updateAnnounceeResponse> CarAppWebClient.CreateAnnouncementService.CreateAnnouncementSoap.updateAnnounceeAsync(CarAppWebClient.CreateAnnouncementService.updateAnnounceeRequest request) {
            return base.Channel.updateAnnounceeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarAppWebClient.CreateAnnouncementService.updateAnnounceeResponse> updateAnnounceeAsync(
                    int CodAnunt, 
                    string caroserie, 
                    string marca, 
                    string model, 
                    string varianta, 
                    int pret, 
                    int an, 
                    int km, 
                    int putere, 
                    int puterekw, 
                    string combustibil, 
                    string cutieviteze, 
                    int cc, 
                    string culoare, 
                    string locatie, 
                    string descriere, 
                    byte[] imgannounce, 
                    byte[] img1, 
                    byte[] img2, 
                    byte[] img3) {
            CarAppWebClient.CreateAnnouncementService.updateAnnounceeRequest inValue = new CarAppWebClient.CreateAnnouncementService.updateAnnounceeRequest();
            inValue.Body = new CarAppWebClient.CreateAnnouncementService.updateAnnounceeRequestBody();
            inValue.Body.CodAnunt = CodAnunt;
            inValue.Body.caroserie = caroserie;
            inValue.Body.marca = marca;
            inValue.Body.model = model;
            inValue.Body.varianta = varianta;
            inValue.Body.pret = pret;
            inValue.Body.an = an;
            inValue.Body.km = km;
            inValue.Body.putere = putere;
            inValue.Body.puterekw = puterekw;
            inValue.Body.combustibil = combustibil;
            inValue.Body.cutieviteze = cutieviteze;
            inValue.Body.cc = cc;
            inValue.Body.culoare = culoare;
            inValue.Body.locatie = locatie;
            inValue.Body.descriere = descriere;
            inValue.Body.imgannounce = imgannounce;
            inValue.Body.img1 = img1;
            inValue.Body.img2 = img2;
            inValue.Body.img3 = img3;
            return ((CarAppWebClient.CreateAnnouncementService.CreateAnnouncementSoap)(this)).updateAnnounceeAsync(inValue);
        }
    }
}
