//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarAppWebClient.BrowseService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BrowseService.BrowseServiceSoap")]
    public interface BrowseServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PopulateAnunturi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet PopulateAnunturi(
                    string marca, 
                    string model, 
                    string pretMin, 
                    string pretMax, 
                    string varianta, 
                    string combustibil, 
                    string anMin, 
                    string anMax, 
                    string ccMin, 
                    string ccMax, 
                    string cpMin, 
                    string cpMax, 
                    string kmMin, 
                    string kmMax, 
                    string caroserie, 
                    string culoare, 
                    string cutieViteze, 
                    string locatie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PopulateAnunturi", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> PopulateAnunturiAsync(
                    string marca, 
                    string model, 
                    string pretMin, 
                    string pretMax, 
                    string varianta, 
                    string combustibil, 
                    string anMin, 
                    string anMax, 
                    string ccMin, 
                    string ccMax, 
                    string cpMin, 
                    string cpMax, 
                    string kmMin, 
                    string kmMax, 
                    string caroserie, 
                    string culoare, 
                    string cutieViteze, 
                    string locatie);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BrowseServiceSoapChannel : CarAppWebClient.BrowseService.BrowseServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrowseServiceSoapClient : System.ServiceModel.ClientBase<CarAppWebClient.BrowseService.BrowseServiceSoap>, CarAppWebClient.BrowseService.BrowseServiceSoap {
        
        public BrowseServiceSoapClient() {
        }
        
        public BrowseServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BrowseServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrowseServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrowseServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet PopulateAnunturi(
                    string marca, 
                    string model, 
                    string pretMin, 
                    string pretMax, 
                    string varianta, 
                    string combustibil, 
                    string anMin, 
                    string anMax, 
                    string ccMin, 
                    string ccMax, 
                    string cpMin, 
                    string cpMax, 
                    string kmMin, 
                    string kmMax, 
                    string caroserie, 
                    string culoare, 
                    string cutieViteze, 
                    string locatie) {
            return base.Channel.PopulateAnunturi(marca, model, pretMin, pretMax, varianta, combustibil, anMin, anMax, ccMin, ccMax, cpMin, cpMax, kmMin, kmMax, caroserie, culoare, cutieViteze, locatie);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> PopulateAnunturiAsync(
                    string marca, 
                    string model, 
                    string pretMin, 
                    string pretMax, 
                    string varianta, 
                    string combustibil, 
                    string anMin, 
                    string anMax, 
                    string ccMin, 
                    string ccMax, 
                    string cpMin, 
                    string cpMax, 
                    string kmMin, 
                    string kmMax, 
                    string caroserie, 
                    string culoare, 
                    string cutieViteze, 
                    string locatie) {
            return base.Channel.PopulateAnunturiAsync(marca, model, pretMin, pretMax, varianta, combustibil, anMin, anMax, ccMin, ccMax, cpMin, cpMax, kmMin, kmMax, caroserie, culoare, cutieViteze, locatie);
        }
    }
}
