//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarAppWebClient.LoginService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Admin", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Admin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prenumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] pozaProfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contactField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nume {
            get {
                return this.numeField;
            }
            set {
                if ((object.ReferenceEquals(this.numeField, value) != true)) {
                    this.numeField = value;
                    this.RaisePropertyChanged("nume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string prenume {
            get {
                return this.prenumeField;
            }
            set {
                if ((object.ReferenceEquals(this.prenumeField, value) != true)) {
                    this.prenumeField = value;
                    this.RaisePropertyChanged("prenume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] pozaProfil {
            get {
                return this.pozaProfilField;
            }
            set {
                if ((object.ReferenceEquals(this.pozaProfilField, value) != true)) {
                    this.pozaProfilField = value;
                    this.RaisePropertyChanged("pozaProfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string contact {
            get {
                return this.contactField;
            }
            set {
                if ((object.ReferenceEquals(this.contactField, value) != true)) {
                    this.contactField = value;
                    this.RaisePropertyChanged("contact");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prenumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonField;
        
        private bool isBannedField;
        
        private int nrAnunturiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] pozaProfilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nume {
            get {
                return this.numeField;
            }
            set {
                if ((object.ReferenceEquals(this.numeField, value) != true)) {
                    this.numeField = value;
                    this.RaisePropertyChanged("nume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string prenume {
            get {
                return this.prenumeField;
            }
            set {
                if ((object.ReferenceEquals(this.prenumeField, value) != true)) {
                    this.prenumeField = value;
                    this.RaisePropertyChanged("prenume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string adresa {
            get {
                return this.adresaField;
            }
            set {
                if ((object.ReferenceEquals(this.adresaField, value) != true)) {
                    this.adresaField = value;
                    this.RaisePropertyChanged("adresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string telefon {
            get {
                return this.telefonField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonField, value) != true)) {
                    this.telefonField = value;
                    this.RaisePropertyChanged("telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool isBanned {
            get {
                return this.isBannedField;
            }
            set {
                if ((this.isBannedField.Equals(value) != true)) {
                    this.isBannedField = value;
                    this.RaisePropertyChanged("isBanned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int nrAnunturi {
            get {
                return this.nrAnunturiField;
            }
            set {
                if ((this.nrAnunturiField.Equals(value) != true)) {
                    this.nrAnunturiField = value;
                    this.RaisePropertyChanged("nrAnunturi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public byte[] pozaProfil {
            get {
                return this.pozaProfilField;
            }
            set {
                if ((object.ReferenceEquals(this.pozaProfilField, value) != true)) {
                    this.pozaProfilField = value;
                    this.RaisePropertyChanged("pozaProfil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginService.LoginServiceSoap")]
    public interface LoginServiceSoap {
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FoundEmail", ReplyAction="*")]
        CarAppWebClient.LoginService.FoundEmailResponse FoundEmail(CarAppWebClient.LoginService.FoundEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FoundEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<CarAppWebClient.LoginService.FoundEmailResponse> FoundEmailAsync(CarAppWebClient.LoginService.FoundEmailRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckPassword", ReplyAction="*")]
        CarAppWebClient.LoginService.CheckPasswordResponse CheckPassword(CarAppWebClient.LoginService.CheckPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<CarAppWebClient.LoginService.CheckPasswordResponse> CheckPasswordAsync(CarAppWebClient.LoginService.CheckPasswordRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnAdmin", ReplyAction="*")]
        CarAppWebClient.LoginService.ReturnAdminResponse ReturnAdmin(CarAppWebClient.LoginService.ReturnAdminRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnAdmin", ReplyAction="*")]
        System.Threading.Tasks.Task<CarAppWebClient.LoginService.ReturnAdminResponse> ReturnAdminAsync(CarAppWebClient.LoginService.ReturnAdminRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnUser", ReplyAction="*")]
        CarAppWebClient.LoginService.ReturnUserResponse ReturnUser(CarAppWebClient.LoginService.ReturnUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CarAppWebClient.LoginService.ReturnUserResponse> ReturnUserAsync(CarAppWebClient.LoginService.ReturnUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FoundEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FoundEmail", Namespace="http://tempuri.org/", Order=0)]
        public CarAppWebClient.LoginService.FoundEmailRequestBody Body;
        
        public FoundEmailRequest() {
        }
        
        public FoundEmailRequest(CarAppWebClient.LoginService.FoundEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FoundEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool isAdmin;
        
        public FoundEmailRequestBody() {
        }
        
        public FoundEmailRequestBody(string email, bool isAdmin) {
            this.email = email;
            this.isAdmin = isAdmin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FoundEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FoundEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarAppWebClient.LoginService.FoundEmailResponseBody Body;
        
        public FoundEmailResponse() {
        }
        
        public FoundEmailResponse(CarAppWebClient.LoginService.FoundEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FoundEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool FoundEmailResult;
        
        public FoundEmailResponseBody() {
        }
        
        public FoundEmailResponseBody(bool FoundEmailResult) {
            this.FoundEmailResult = FoundEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckPassword", Namespace="http://tempuri.org/", Order=0)]
        public CarAppWebClient.LoginService.CheckPasswordRequestBody Body;
        
        public CheckPasswordRequest() {
        }
        
        public CheckPasswordRequest(CarAppWebClient.LoginService.CheckPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string parola;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool isAdmin;
        
        public CheckPasswordRequestBody() {
        }
        
        public CheckPasswordRequestBody(string email, string parola, bool isAdmin) {
            this.email = email;
            this.parola = parola;
            this.isAdmin = isAdmin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarAppWebClient.LoginService.CheckPasswordResponseBody Body;
        
        public CheckPasswordResponse() {
        }
        
        public CheckPasswordResponse(CarAppWebClient.LoginService.CheckPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckPasswordResult;
        
        public CheckPasswordResponseBody() {
        }
        
        public CheckPasswordResponseBody(bool CheckPasswordResult) {
            this.CheckPasswordResult = CheckPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnAdmin", Namespace="http://tempuri.org/", Order=0)]
        public CarAppWebClient.LoginService.ReturnAdminRequestBody Body;
        
        public ReturnAdminRequest() {
        }
        
        public ReturnAdminRequest(CarAppWebClient.LoginService.ReturnAdminRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnAdminRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public ReturnAdminRequestBody() {
        }
        
        public ReturnAdminRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnAdminResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarAppWebClient.LoginService.ReturnAdminResponseBody Body;
        
        public ReturnAdminResponse() {
        }
        
        public ReturnAdminResponse(CarAppWebClient.LoginService.ReturnAdminResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnAdminResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarAppWebClient.LoginService.Admin ReturnAdminResult;
        
        public ReturnAdminResponseBody() {
        }
        
        public ReturnAdminResponseBody(CarAppWebClient.LoginService.Admin ReturnAdminResult) {
            this.ReturnAdminResult = ReturnAdminResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnUser", Namespace="http://tempuri.org/", Order=0)]
        public CarAppWebClient.LoginService.ReturnUserRequestBody Body;
        
        public ReturnUserRequest() {
        }
        
        public ReturnUserRequest(CarAppWebClient.LoginService.ReturnUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public ReturnUserRequestBody() {
        }
        
        public ReturnUserRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public CarAppWebClient.LoginService.ReturnUserResponseBody Body;
        
        public ReturnUserResponse() {
        }
        
        public ReturnUserResponse(CarAppWebClient.LoginService.ReturnUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarAppWebClient.LoginService.User ReturnUserResult;
        
        public ReturnUserResponseBody() {
        }
        
        public ReturnUserResponseBody(CarAppWebClient.LoginService.User ReturnUserResult) {
            this.ReturnUserResult = ReturnUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginServiceSoapChannel : CarAppWebClient.LoginService.LoginServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceSoapClient : System.ServiceModel.ClientBase<CarAppWebClient.LoginService.LoginServiceSoap>, CarAppWebClient.LoginService.LoginServiceSoap {
        
        public LoginServiceSoapClient() {
        }
        
        public LoginServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarAppWebClient.LoginService.FoundEmailResponse CarAppWebClient.LoginService.LoginServiceSoap.FoundEmail(CarAppWebClient.LoginService.FoundEmailRequest request) {
            return base.Channel.FoundEmail(request);
        }
        
        public bool FoundEmail(string email, bool isAdmin) {
            CarAppWebClient.LoginService.FoundEmailRequest inValue = new CarAppWebClient.LoginService.FoundEmailRequest();
            inValue.Body = new CarAppWebClient.LoginService.FoundEmailRequestBody();
            inValue.Body.email = email;
            inValue.Body.isAdmin = isAdmin;
            CarAppWebClient.LoginService.FoundEmailResponse retVal = ((CarAppWebClient.LoginService.LoginServiceSoap)(this)).FoundEmail(inValue);
            return retVal.Body.FoundEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarAppWebClient.LoginService.FoundEmailResponse> CarAppWebClient.LoginService.LoginServiceSoap.FoundEmailAsync(CarAppWebClient.LoginService.FoundEmailRequest request) {
            return base.Channel.FoundEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarAppWebClient.LoginService.FoundEmailResponse> FoundEmailAsync(string email, bool isAdmin) {
            CarAppWebClient.LoginService.FoundEmailRequest inValue = new CarAppWebClient.LoginService.FoundEmailRequest();
            inValue.Body = new CarAppWebClient.LoginService.FoundEmailRequestBody();
            inValue.Body.email = email;
            inValue.Body.isAdmin = isAdmin;
            return ((CarAppWebClient.LoginService.LoginServiceSoap)(this)).FoundEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarAppWebClient.LoginService.CheckPasswordResponse CarAppWebClient.LoginService.LoginServiceSoap.CheckPassword(CarAppWebClient.LoginService.CheckPasswordRequest request) {
            return base.Channel.CheckPassword(request);
        }
        
        public bool CheckPassword(string email, string parola, bool isAdmin) {
            CarAppWebClient.LoginService.CheckPasswordRequest inValue = new CarAppWebClient.LoginService.CheckPasswordRequest();
            inValue.Body = new CarAppWebClient.LoginService.CheckPasswordRequestBody();
            inValue.Body.email = email;
            inValue.Body.parola = parola;
            inValue.Body.isAdmin = isAdmin;
            CarAppWebClient.LoginService.CheckPasswordResponse retVal = ((CarAppWebClient.LoginService.LoginServiceSoap)(this)).CheckPassword(inValue);
            return retVal.Body.CheckPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarAppWebClient.LoginService.CheckPasswordResponse> CarAppWebClient.LoginService.LoginServiceSoap.CheckPasswordAsync(CarAppWebClient.LoginService.CheckPasswordRequest request) {
            return base.Channel.CheckPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarAppWebClient.LoginService.CheckPasswordResponse> CheckPasswordAsync(string email, string parola, bool isAdmin) {
            CarAppWebClient.LoginService.CheckPasswordRequest inValue = new CarAppWebClient.LoginService.CheckPasswordRequest();
            inValue.Body = new CarAppWebClient.LoginService.CheckPasswordRequestBody();
            inValue.Body.email = email;
            inValue.Body.parola = parola;
            inValue.Body.isAdmin = isAdmin;
            return ((CarAppWebClient.LoginService.LoginServiceSoap)(this)).CheckPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarAppWebClient.LoginService.ReturnAdminResponse CarAppWebClient.LoginService.LoginServiceSoap.ReturnAdmin(CarAppWebClient.LoginService.ReturnAdminRequest request) {
            return base.Channel.ReturnAdmin(request);
        }
        
        public CarAppWebClient.LoginService.Admin ReturnAdmin(string email) {
            CarAppWebClient.LoginService.ReturnAdminRequest inValue = new CarAppWebClient.LoginService.ReturnAdminRequest();
            inValue.Body = new CarAppWebClient.LoginService.ReturnAdminRequestBody();
            inValue.Body.email = email;
            CarAppWebClient.LoginService.ReturnAdminResponse retVal = ((CarAppWebClient.LoginService.LoginServiceSoap)(this)).ReturnAdmin(inValue);
            return retVal.Body.ReturnAdminResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarAppWebClient.LoginService.ReturnAdminResponse> CarAppWebClient.LoginService.LoginServiceSoap.ReturnAdminAsync(CarAppWebClient.LoginService.ReturnAdminRequest request) {
            return base.Channel.ReturnAdminAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarAppWebClient.LoginService.ReturnAdminResponse> ReturnAdminAsync(string email) {
            CarAppWebClient.LoginService.ReturnAdminRequest inValue = new CarAppWebClient.LoginService.ReturnAdminRequest();
            inValue.Body = new CarAppWebClient.LoginService.ReturnAdminRequestBody();
            inValue.Body.email = email;
            return ((CarAppWebClient.LoginService.LoginServiceSoap)(this)).ReturnAdminAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarAppWebClient.LoginService.ReturnUserResponse CarAppWebClient.LoginService.LoginServiceSoap.ReturnUser(CarAppWebClient.LoginService.ReturnUserRequest request) {
            return base.Channel.ReturnUser(request);
        }
        
        public CarAppWebClient.LoginService.User ReturnUser(string email) {
            CarAppWebClient.LoginService.ReturnUserRequest inValue = new CarAppWebClient.LoginService.ReturnUserRequest();
            inValue.Body = new CarAppWebClient.LoginService.ReturnUserRequestBody();
            inValue.Body.email = email;
            CarAppWebClient.LoginService.ReturnUserResponse retVal = ((CarAppWebClient.LoginService.LoginServiceSoap)(this)).ReturnUser(inValue);
            return retVal.Body.ReturnUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarAppWebClient.LoginService.ReturnUserResponse> CarAppWebClient.LoginService.LoginServiceSoap.ReturnUserAsync(CarAppWebClient.LoginService.ReturnUserRequest request) {
            return base.Channel.ReturnUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarAppWebClient.LoginService.ReturnUserResponse> ReturnUserAsync(string email) {
            CarAppWebClient.LoginService.ReturnUserRequest inValue = new CarAppWebClient.LoginService.ReturnUserRequest();
            inValue.Body = new CarAppWebClient.LoginService.ReturnUserRequestBody();
            inValue.Body.email = email;
            return ((CarAppWebClient.LoginService.LoginServiceSoap)(this)).ReturnUserAsync(inValue);
        }
    }
}
